blog/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = 'blog'
urlpatterns = [
    path('main/', views.MainPageView.as_view(), name='main_page'),
    path('', cache_page(60)(views.PostListView.as_view()), name='post_list'),
    path('post/<slug:slug>/', cache_page(60)(views.PostDetailView.as_view()), name='post_detail'),
    path('new_post/', cache_page(60)(views.PostCreateView.as_view()), name='create_post'),
    path('post/<slug:slug>/edit/', views.PostEditView.as_view(), name='edit_post'),
    path('post/<slug:slug>/delete/', views.PostDeleteView.as_view(), name='delete_post'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('newsletter/', include('mailing_creation.urls', namespace='mailing_creation')),
    path('', include('blog.urls', namespace='blog'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_creation/urls.py
from django.urls import path
from .views import HomeView, CreateNewsletter, UpdateNewsletter, ReadNewsletter, DeleteNewsletterView, PauseTaskView
from django.views.decorators.cache import cache_page
app_name = 'mailing_creation'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('create/', cache_page(60)(CreateNewsletter.as_view()), name='create_newsletter'),
    path('newsletter/<int:pk>/', ReadNewsletter.as_view(), name='newsletter_info'),
    path('update/<int:pk>/', UpdateNewsletter.as_view(), name='update_newsletter'),
    path('delete_newsletter/<int:model_id>/', DeleteNewsletterView.as_view(), name='delete_newsletter'),
    path('pause_task/<int:model_id>/', PauseTaskView.as_view(), name='pause_task'),
]

users/urls.py
from django.contrib.auth import views
from django.urls import path
from users.views import RegisterView, UserConfirmEmailView, send_new_password, ProfileView, DeleteProfile
app_name = 'users'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('confirm-email/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_mail'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('delete_account/<int:pk>/', DeleteProfile.as_view(), name='delete_account'),
    path('profile/genpassword/', send_new_password, name='send_new_password'),
]

mailing_creation/models.py
from django.db import models
from django.conf import settings
from django.contrib.postgres.fields import ArrayField

class Newsletter(models.Model):
    delivery_time = models.DateTimeField(verbose_name='Дата начала рассылки')
    end_delivery_time = models.DateTimeField(verbose_name='Дата окончания рассылки')
    creation_date = models.DateTimeField(auto_now_add=True,
                                         verbose_name='Дата создания')
    frequency = models.CharField(max_length=40,
                                 verbose_name='Периодичность отправки',
                                 choices=[('daily', 'Раз в день'),
                                          ('weekly', 'Раз в неделю'),
                                          ('monthly', 'Раз в месяц')],
                                 default='monthly')

    status = models.CharField(max_length=40,
                              choices=[('completed', 'Завершена'),
                                       ('created', 'Создана'),
                                       ('running', 'Запущена'),
                                       ('paused', 'Приостановлена')],
                              default='created')

    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.SET_NULL,
                                verbose_name='Создатель',
                                null=True, blank=True)

    task_id = models.CharField(max_length=100, blank=True, null=True)

    recipients = ArrayField(models.CharField(max_length=100), default=list, verbose_name='Получатели')

    def __str__(self):
        return f'Рассылка {self.pk}'

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        permissions = [
            (
                'start_and_stop_newsletter',
                'Can start and stop newsletter'
            )
        ]


class NewsletterMessage(models.Model):
    newsletter = models.ForeignKey(Newsletter, on_delete=models.CASCADE)
    theme = models.CharField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return self.theme

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class NewsletterLog(models.Model):
    newsletter = models.ForeignKey(NewsletterMessage, on_delete=models.CASCADE)
    attempt_datetime = models.DateTimeField(auto_now_add=True)
    attempt_status = models.CharField(max_length=20)
    mail_server_response = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'Лог рассылки {self.newsletter.pk}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

mailing_creation/forms.py
from django import forms
from .models import Newsletter, NewsletterMessage
from django.contrib.postgres.fields import ArrayField

class CreateNewsletterForm(forms.ModelForm):
    delivery_time = forms.DateTimeField(widget=forms.widgets.DateInput(attrs={'type': 'datetime-local'}))
    end_delivery_time = forms.DateTimeField(widget=forms.widgets.DateInput(attrs={'type': 'datetime-local'}))
    recipients = ArrayField(forms.CharField(max_length=100), default=list, verbose_name='Получатели')
    class Meta:
        model = Newsletter
        fields = ['delivery_time', 'end_delivery_time', 'frequency', 'recipients']


class CreateNewsletterMessageForm(forms.ModelForm):
    class Meta:
        model = NewsletterMessage
        fields = ['theme', 'body', ]

mailing_creation/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import Newsletter, NewsletterMessage, NewsletterLog
from django.views.generic import ListView, DetailView, View, CreateView, UpdateView, FormView
from .forms import CreateNewsletterForm, CreateNewsletterMessageForm
from .tasks import scheduler


class HomeView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Newsletter
    permission_required = 'mailing_creation.view_newsletter'
    template_name = 'mailing_creation/newsletter_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['newsletters'] = Newsletter.objects.filter(creator_id=self.request.user.id)
        return context


class CreateNewsletter(LoginRequiredMixin, PermissionRequiredMixin, FormView):
    permission_required = 'mailing_creation.add_newsletter'
    template_name = 'mailing_creation/newsletter_form.html'
    form_class = CreateNewsletterForm
    second_form_class = CreateNewsletterMessageForm
    success_url = reverse_lazy('mailing_creation:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['newsletter_form'] = context['form']
        context['newsletter_message_form'] = self.second_form_class()
        return context

    def form_valid(self, form):
        # Обработка первой формы
        newsletter = form.save(commit=False)
        newsletter.creator = self.request.user
        newsletter.save()

        # Обработка второй формы
        second_form = self.second_form_class(self.request.POST)
        if second_form.is_valid():
            newsletter_message = second_form.save(commit=False)
            newsletter_message.newsletter = newsletter
            newsletter_message.save()

        return super().form_valid(form)


class UpdateNewsletter(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Newsletter
    permission_required = 'mailing_creation.change_newsletter'
    form_class = CreateNewsletterForm
    template_name = 'mailing_creation/newsletter_form.html'
    success_url = reverse_lazy('mailing_creation:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        newsletter_message = NewsletterMessage.objects.get(newsletter=self.object)
        context['newsletter_message_form'] = CreateNewsletterMessageForm(instance=newsletter_message)
        return context

    def form_valid(self, form):
        # Обработка первой формы
        newsletter = form.save(commit=False)
        newsletter.save()

        # Обработка второй формы
        newsletter_message = NewsletterMessage.objects.get(newsletter=newsletter)
        second_form = CreateNewsletterMessageForm(self.request.POST, instance=newsletter_message)
        if second_form.is_valid():
            second_form.save()

        return super().form_valid(form)


class ReadNewsletter(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Newsletter
    permission_required = 'mailing_creation.view_newsletter'
    template_name = 'mailing_creation/newsletter_info.html'
    context_object_name = 'newsletter'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['newsletter_message'] = NewsletterMessage.objects.get(newsletter=self.object)
        context['newsletter_log'] = context['newsletter_message']
        return context


class DeleteNewsletterView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'mailing_creation.delete_newsletter'

    def get(self, request, model_id):
        my_model = get_object_or_404(Newsletter, id=model_id)
        task_id = my_model.task_id
        if task_id:
            scheduler.remove_job(task_id)
            my_model.task_id = None
            my_model.save()
        my_model.delete()
        return redirect("mailing_creation:home")


class PauseTaskView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = 'mailing_creation.start_and_stop_newsletter'

    def get(self, request, model_id):
        my_model = get_object_or_404(Newsletter, id=model_id)
        task_id = my_model.task_id
        if task_id:
            if my_model.status == 'paused' or my_model.status == 'completed':
                scheduler.resume_job(task_id)
                my_model.status = 'created'
                my_model.save()
            else:
                scheduler.pause_job(task_id)
                my_model.status = 'paused'
                my_model.save()
        return redirect("mailing_creation:home")

mailing_creation/templates/mailing_creation/base.html
<!doctype  html>
<html  lang="ru">
<head>
<link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
<title>SubscribeSync</title>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <a class="my-0 mr-md-auto font-weight-normal h1 text-primary" href="{% url 'blog:main_page' %}">SubscribeSync</a>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'mailing_creation:home' %}">Рассылки</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:post_list' %}">Блог </a>
{#        <a class="p-2 btn btn-outline-primary" href="{% url 'post_list' %}">Блог</a>#}
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' pk=user.pk %}">Профиль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>
        {% endif %}
    </nav>
</div>
  <div  class="container">
    {% block content %}

    {% endblock %}
  </div>
</body>
</html>

mailing_creation/templates/mailing_creation/newsletter_form.html
{% extends "mailing_creation/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post">
        <div class="row">
            <div class="card col-3">
                <div class="card-body">
                    <h4 class="card-title">Установить дату</h4>
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}">

                    {{ form|crispy }}
                </div>
            </div>
            <div class="card col">
                <div class="card-body">
                    <h4 class="card-title">Создать письмо</h4>
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}">

                    {{ newsletter_message_form|crispy }}

                    <button type="submit" class="btn btn-primary btn-block">Создать</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

mailing_creation/templates/mailing_creation/newsletter_info.html
{% extends "mailing_creation/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card mb-3">
        <div class="card-header h1">{{ newsletter_message.theme }}</div>
        <div class="row g-0">
            <div class="col-md-4 border-right">
                <div class="card-body">
                    <p class="card-text"><small class="text-muted">Создано: {{ newsletter.creation_date }}</small></p>
                    <p class="card-text"><small class="text-muted">Отправка: {{ newsletter.delivery_time }}</small></p>
                    <p class="card-text"><small class="text-muted">Создатель: {{ newsletter.creator }}</small></p>
                    <p class="card-text"><small
                            class="text-muted">Получатели: {{ newsletter.recipients|join:", " }}</small></p>
                </div>
            </div>
            <div class="col">
                <div class="card-body ">
                    <p class="card-text">{{ newsletter_message.body }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing_creation/templates/mailing_creation/newsletter_list.html
{% extends "mailing_creation/base.html" %}
{% load static %}

{% block title %}Главная страница - SubscribeSync{% endblock %}

{% block content %}
    <div class="row text-center">
        {% if user.is_authenticated %}
            <div class="col-12 mb-5">
                <a class="btn btn-outline-primary" href="{% url 'mailing_creation:create_newsletter' %}">Создать
                    рассылку</a>
            </div>
        {% endif %}
        {% for newsletter in newsletters %}
            {% for message in newsletter.newslettermessage_set.all %}
                <div class="col-4 mb-4">

                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">Тема: {{ message.theme }}</h5>
                        </div>
                        <div class="card-body">
                            <p class="card-text {% if newsletter.status == 'completed' %}text-success{% elif newsletter.status == 'running' %}text-warning{% elif newsletter.status == 'paused' %} text-danger {% else %}text-primary{% endif %}">
                                Статус: {{ newsletter.get_status_display }}</p>
                            <p class="card-text">Периодичность отправки: {{ newsletter.get_frequency_display }}</p>
                            <p class="card-text">Дата отправки: {{ newsletter.delivery_time }}</p>
                            {% if user.is_authenticated %}
                                <a href="{% url 'mailing_creation:update_newsletter' newsletter.pk %}"
                                   class="btn btn-outline-primary btn-block">Изменить</a>
                                <a href="{% url 'mailing_creation:newsletter_info' newsletter.pk %}"
                                   class="btn btn-outline-primary btn-block">Подробнее</a>
                                {% if newsletter.status == 'completed' or newsletter.status == 'paused' %}
                                    <a href="{% url 'mailing_creation:pause_task' newsletter.id %}"
                                       class="btn btn-success btn-block">Возобновить</a>
                                {% else %}
                                    <a href="{% url 'mailing_creation:pause_task' newsletter.id %}"
                                       class="btn btn-danger btn-block">Пауза</a>
                                {% endif %}
                                <a href="{% url 'mailing_creation:delete_newsletter' newsletter.id %}"
                                   class="btn btn-danger btn-block">Удалить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endfor %}
    </div>
{% endblock %}