blog/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = 'blog'
urlpatterns = [
    path('main/', views.MainPageView.as_view(), name='main_page'),
    path('', cache_page(60)(views.PostListView.as_view()), name='post_list'),
    path('post/<slug:slug>/', cache_page(60)(views.PostDetailView.as_view()), name='post_detail'),
    path('new_post/', cache_page(60)(views.PostCreateView.as_view()), name='create_post'),
    path('post/<slug:slug>/edit/', views.PostEditView.as_view(), name='edit_post'),
    path('post/<slug:slug>/delete/', views.PostDeleteView.as_view(), name='delete_post'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('newsletter/', include('mailing_creation.urls', namespace='mailing_creation')),
    path('', include('blog.urls', namespace='blog'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify


class BlogPost(models.Model):
    title = models.CharField(max_length=200, verbose_name='название')
    slug = models.CharField(max_length=200, unique=True, verbose_name='slug')
    content = models.TextField(verbose_name='содержание')
    preview_image = models.ImageField(upload_to='blog_images/', verbose_name='превью')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='статус публикации')
    views_count = models.PositiveIntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

    def add_view(self):
        self.views_count += 1
        self.save()

    def save(self, *args, **kwargs):
        # Генерируем slug из заголовка поста
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

blog/forms.py
from django import forms
from blog.models import BlogPost


class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'content', 'preview_image', 'is_published']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from .models import BlogPost
from blog.forms import BlogPostForm
from mailing_creation.models import Newsletter, NewsletterMessage
import random
from django.db.models import Count


class MainPageView(TemplateView):
    template_name = 'blog/main_page.html'

    def get_context_data(self, **kwargs):
        context = {}
        posts = BlogPost.objects.all()
        if posts:
            random_numbers = random.sample(range(len(posts)), min(3, len(posts)))
            random_posts = [posts[i] for i in random_numbers]
            context['posts'] = random_posts
        context['newsletter_count'] = Newsletter.objects.count()
        context['newsletter_active'] = Newsletter.objects.filter(status__in=['created', 'running']).count()
        recipients_count = []
        for i in Newsletter.objects.all():
            recipients_count.extend(i.recipients)
        context['unique_recipients'] = len(set(recipients_count))
        return context


class PostListView(ListView):
    model = BlogPost
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    queryset = BlogPost.objects.filter(is_published=True).order_by('-created_date')


class PostDetailView(DetailView):
    model = BlogPost
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'
    slug_url_kwarg = 'slug'
    queryset = BlogPost.objects.filter(is_published=True)

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.add_view()
        return self.object


class PostEditView(View):
    template_name = 'blog/edit_form.html'

    def get(self, request, slug):
        post = get_object_or_404(BlogPost, slug=slug, is_published=True)
        form = BlogPostForm(instance=post)
        return render(request, self.template_name, {'form': form, 'post': post})

    def post(self, request, slug):
        post = get_object_or_404(BlogPost, slug=slug, is_published=True)
        form = BlogPostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:post_detail', slug=post.slug)


class PostCreateView(CreateView):
    template_name = 'blog/create_form.html'

    def get(self, request):
        form = BlogPostForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = BlogPostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            return redirect('blog:post_detail', slug=post.slug)


class PostDeleteView(View):

    def get(self, request, slug):
        posts = BlogPost.objects.filter(is_published=True).order_by('-created_date')
        post = get_object_or_404(BlogPost, slug=slug, is_published=True)
        post.delete()
        return render(request, 'blog/post_list.html', {'posts': posts})

blog/templates/blog/create_form.html
{% extends 'mailing_creation/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Create a New Blog Post</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Create Post</button>
    </form>
{% endblock %}

blog/templates/blog/edit_form.html
{% extends 'mailing_creation/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Edit Post</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Save Changes</button>
    </form>
    <a href="{% url 'blog:post_detail' slug=post.slug %}">Cancel</a>
{% endblock %}

blog/templates/blog/main_page.html
{% extends 'mailing_creation/base.html' %}

{% block content %}
    <h1 class="mt-4 mb-4 text-center">Добро пожаловать!</h1>
    <div class="row mx-auto mb-3">
        <div class="col-3 text-white bg-info border mx-auto p-lg-3 rounded">Всего рассылок: {{ newsletter_count }}</div>
        <div class="col-3 text-white bg-info border mx-auto p-lg-3 rounded">Активных рассылок: {{ newsletter_active }}</div>
        <div class="col-3 text-white bg-info border mx-auto p-lg-3 rounded">Уникальных клиентов: {{ unique_recipients }}</div>
    </div>
    {% for post in posts %}
        <li class="list-group-item bg-light">
            <div class="row">
                <div class="col-3 border-right">
                    <img src="{{ post.preview_image.url }}" alt="{{ post.title }}" class="img-fluid mb-4 rounded">
                </div>
                <div class="col-9">
                    <h2><a href="{% url 'blog:post_detail' slug=post.slug %}">{{ post.title }}</a></h2>
                    <p>Дата создания: {{ post.created_date }}</p>
                    <p>Количество просмотров: {{ post.views_count }}</p>
                    <p>{{ post.content | safe }}</p>
                </div>
            </div>
        </li>
    {% empty %}
        <li class="list-group-item">Нет доступных блоговых записей.</li>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'mailing_creation/base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h1 class="card-title">{{ post.title }}</h1>
          <p class="card-text text-muted">Опубликовано {{ post.created_date|date:"d F Y" }}<br>Просмотров: {{ post.views_count }}</p>
          <img src="{{ post.preview_image.url }}" alt="{{ post.title }}" class="img-fluid mb-4">
          <p class="card-text">{{ post.content }}</p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Другие записи</h5>
          <ul class="list-group">
            {% for other_post in other_posts %}
            <li class="list-group-item">
              <a href="{% url 'blog:post_detail' slug=other_post.slug %}">{{ other_post.title }}</a>
            </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-3">
    <a class="btn btn-outline-primary" href="delete/">Удалить</a>
    <a class="btn btn-outline-primary" href="edit/">Редактировать</a>
  </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'mailing_creation/base.html' %}

{% block content %}
<h1 class="mt-4 mb-4 text-center">Список блоговых записей</h1>
<ul class="list-group">
  {% for post in posts %}
    <li class="list-group-item">
      <h2><a href="{% url 'blog:post_detail' slug=post.slug %}">{{ post.title }}</a></h2>
      <p>Дата создания: {{ post.created_date }}</p>
      <p>Количество просмотров: {{ post.views_count }}</p>
      <p>{{ post.content | safe }}</p>
    </li>
  {% empty %}
    <li class="list-group-item">Нет доступных блоговых записей.</li>
  {% endfor %}
  <div class="mt-3">
    <a class="btn btn-outline-primary" href="{% url 'blog:create_post' %}">Новая запись</a>
  </div>
</ul>
{% endblock %}