blog/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = 'blog'
urlpatterns = [
    path('main/', views.MainPageView.as_view(), name='main_page'),
    path('', cache_page(60)(views.PostListView.as_view()), name='post_list'),
    path('post/<slug:slug>/', cache_page(60)(views.PostDetailView.as_view()), name='post_detail'),
    path('new_post/', cache_page(60)(views.PostCreateView.as_view()), name='create_post'),
    path('post/<slug:slug>/edit/', views.PostEditView.as_view(), name='edit_post'),
    path('post/<slug:slug>/delete/', views.PostDeleteView.as_view(), name='delete_post'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('newsletter/', include('mailing_creation.urls', namespace='mailing_creation')),
    path('', include('blog.urls', namespace='blog'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views
from django.urls import path
from users.views import RegisterView, UserConfirmEmailView, send_new_password, ProfileView, DeleteProfile
app_name = 'users'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('confirm-email/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_mail'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('delete_account/<int:pk>/', DeleteProfile.as_view(), name='delete_account'),
    path('profile/genpassword/', send_new_password, name='send_new_password'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class CustomUser(AbstractUser):
    username = None

    email = models.EmailField(verbose_name='почта', unique=True)
    full_name = models.CharField(max_length=250, verbose_name='ФИО')
    about = models.TextField(verbose_name='Комментарий', blank=True)

    token = models.CharField(max_length=200, verbose_name='токен верификации', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'full_name')


class CustomUserUpdateForm(UserChangeForm):
    password = None

    class Meta:
        model = CustomUser
        fields = ('full_name', 'about')

users/views.py
from django.views.generic.edit import CreateView
from django.shortcuts import redirect
from .models import CustomUser
from django.views import View
from .forms import CustomUserCreationForm, CustomUserUpdateForm
from django.urls import reverse_lazy, reverse
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView, DeleteView
from config import settings
import secrets
from django.contrib.auth.models import Group


class RegisterView(CreateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'users/customuser_form.html'
    success_url = reverse_lazy('mailing_creation:home')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        token = secrets.token_urlsafe(nbytes=8)

        user.token = token
        activate_url = reverse_lazy('users:confirm_mail', kwargs={'token': user.token})
        send_mail(
            subject='Подтверждение почты',
            message=f'Для подтверждения регистрации перейдите по ссылке: http://localhost:8000/{activate_url}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
            fail_silently=False
        )
        user.save()

        return redirect('/')


class UserConfirmEmailView(View):
    def get(self, request, token):
        user = CustomUser.objects.get(token=token)
        user.groups.add(Group.objects.get(name='User'))
        user.is_active = True
        user.token = None
        user.save()
        return redirect('users:login')


class ProfileView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserUpdateForm
    template_name = 'users/profile_detail.html'
    success_url = reverse_lazy('blog:main_page')

class DeleteProfile(LoginRequiredMixin, DeleteView):
    model = CustomUser
    success_url = reverse_lazy('blog:main_page')


def send_new_password(request):
    new_password = secrets.token_hex(nbytes=8)
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('blog:main_page'))

users/templates/users/base.html
<!doctype  html>
<html  lang="en">
<head>
<link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
<title>SubscribeSync</title>
</head>
<body>
  <div  class="container">
    <div  class="row justify-content-center">
      <div  class="col-4">
      <h1  class="text-center">SubscribeSync</h1>
      {% block main %}
      {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

users/templates/users/customuser_confirm_delete.html
{% extends  "users/base.html" %}

{% block main %}
    <div class="center">
        <form method="post" class="card">
            {% csrf_token %}
            <h2>Delete Task</h2>
            <p>Are you sure that you want to delete "{{ customuser }}"?</p>
            <p class="form-buttons">
                <input type="submit" class="btn btn-primary" value="Delete">
                <a href="{% url 'users:profile' %}" class="btn btn-outline">Cancel</a>
            </p>
        </form>
    </div>

{% endblock %}

users/templates/users/customuser_form.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}


{% block main %}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Создать аккаунт</h4>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">

            {{ form|crispy }}

            <button type="submit" class="btn btn-primary btn-block">Зарегистрироваться</button>
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/profile_detail.html
{% extends  "mailing_creation/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Редактировать профиль</h4>
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}">
                        {{ form|crispy }}

                        <button type="submit" class="btn btn-primary btn-block">Подтвердить</button>
                        <a class="p-2 btn btn-danger btn-block"
                           href="{% url 'users:delete_account' customuser.id %}">Удалить</a>
                        <a class="p-2 btn btn-outline-primary btn-block" href="{% url 'users:logout' %}">Выйти</a>
                        <a class="p-2 btn btn-outline-warning btn-block" href="{% url 'users:send_new_password' %}">Сбросить
                            пароль</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}